openapi: 3.0.0
info:
  title: Sample API
  description: A sample API to illustrate OpenAPI concepts
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
    description: Sample API Server
paths:
  /users:
    get:
      summary: Get a list of users
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json: 
              schema: 
                type: array
                items: 
                  type: string
  /users/{id}:
    get:
      summary: Get a user by ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the user to retrieve
          schema:
            type: string
      responses:
        '200':
          description: A single user
          content:
            application/json: 
              schema: 
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
